name: Code to Resume

on:
  push:
    paths:
      - '*.tex'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Compile LaTeX to PDF
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error -output-directory=. resume-as-code.tex
          mv resume-as-code.pdf resume.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: resume.pdf

  publish:
    runs-on: ubuntu-latest
    needs: compile
    if: success()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: compiled-pdf
          path: .

      - name: Commit and Push PDF
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add resume.pdf
          git commit -m "Created by the GitHub Actions Workflow"
          git push      
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
